# Generated by Django 3.2.8 on 2026-03-01

from django.db import migrations, models
from django.utils.text import slugify


def _generate_unique_slug(post_model, post):
    base_slug = slugify(post.title)[:100] or "post"
    candidate = base_slug
    index = 2
    while post_model.objects.exclude(pk=post.pk).filter(slug=candidate).exists():
        suffix = f"-{index}"
        candidate = f"{base_slug[: 120 - len(suffix)]}{suffix}"
        index += 1
    return candidate


def populate_post_slugs(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.all().order_by("id"):
        if post.slug:
            continue
        post.slug = _generate_unique_slug(Post, post)
        post.save(update_fields=["slug"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.RunPython(populate_post_slugs, noop_reverse),
    ]
